- app/controllers/home_controller.rb
- app/mailers/notification_mailer.rb
- app/views/entities/_actions.html.erb
- app/views/home/_contact_header.html.erb
- app/views/home/_form_part_name_email.html.erb
- app/views/home/contact.html.erb
- app/views/home/flag.html.erb
- app/views/notification_mailer/flag_email.html.erb
- config/routes.rb
- spec/controllers/home_controller_spec.rb
- spec/mailers/notification_mailer_spec.rb
- spec/views/home/contact.html.erb_spec.rb
- spec/views/home/flag.html.erb_spec.rb
> New 'flag for review' page

- .gitignore
- app/controllers/home_controller.rb
- app/controllers/lists_controller.rb
- app/models/list.rb
- app/models/user.rb
- app/views/home/dashboard.html.erb
- app/views/lists/_form.html.erb
- app/views/lists/new.html.erb
- config/routes.rb
- db/migrate/20170227163755_add_private_option_to_lists.rb
- db/migrate/20170227190903_add_creator_user_id_to_lists.rb
- db/schema.rb
- db/structure.sql
- spec/controllers/home_controller_spec.rb
- spec/controllers/lists_controller_spec.rb
- spec/models/list_spec.rb
- spec/models/user_spec.rb
- spec/views/lists/new.html.erb_spec.rb
Resolves #20 and #22: associates lists with their creator, and allows that user to see the lists they have created.
> List creator

- app/utility/ls_date.rb
- app/validators/date_validator.rb
- spec/utility/ls_date_spec.rb
Use it to wrap the start_date and end_date.
Dates can be compared.
call `.display` to get a display str for the profile pages.
> LsDate Class

- app/models/relationship.rb
- app/views/entities/show.html.erb
- spec/models/relationship_spec.rb
- spec/views/entities/show.html.erb_spec.rb
* update entities after relationship change
* set page title
> Profile page 3

- app/assets/javascripts/common/utility.js
- app/assets/javascripts/pages/addRelationship.js
- app/assets/stylesheets/base/helpers.scss
- app/assets/stylesheets/styles/entities.scss
- app/controllers/relationships_controller.rb
- app/models/concerns/similar_relationships.rb
- app/models/relationship.rb
- app/views/entities/_add_relationship_form.html.erb
- app/views/entities/add_relationship.html.erb
- config/routes.rb
- spec/controllers/relationships_controller_spec.rb
- spec/factories/users.rb
- spec/javascripts/common/utility.spec.js
- spec/models/relationship_spec.rb
New route: ``` /relationships/find_similar ``` with required params: entity1_id, entity2_id, category_id
New class method on Relationship: ``` Relationship.find_similar ```
New instance method on Relationship: ``` Relationship.new.find_similar ```
> Similar relationships

- app/controllers/api/api_controller.rb
- app/controllers/api/entities_controller.rb
- app/controllers/search_controller.rb
- app/helpers/api_helper.rb
- app/models/concerns/entity_search.rb
- app/models/entity.rb
- app/utility/api_utils/api_response_meta.rb
- app/utility/api_utils/response.rb
- app/views/api/index.html.erb
- config/routes.rb
- spec/api/api_utils_api_response_meta_spec.rb
- spec/api/entities_controller_spec.rb
- spec/api/routes_spec.rb
- spec/controllers/search_controller_spec.rb
- spec/models/entity_spec.rb
allow searching for entities: ``` /entities/search?q=NAME ```
adds pageCount and currentPage to meta object in response.
> entity search api route: /api/entities/search

- .travis.yml
- app/models/relationship.rb
- app/validators/relationship_validator.rb
- db/seeds.rb
- spec/controllers/relationships_controller_spec.rb
- spec/models/relationship_spec.rb
- spec/validators/relationship_validator_spec.rb
> Validate Relationship Categories before saving to database

- app/assets/javascripts/pages/referenceModal.js
- app/views/shared/_reference_new.html.erb
fixes bug where publication_date doesn't get recorded in new references
> fixes new reference modal to actually submit pub date to db

- app/assets/javascripts/pages/bulkAdd.js
- app/assets/stylesheets/base/spin.css
- app/assets/stylesheets/main.scss
- app/assets/stylesheets/styles/tools.scss
- app/views/tools/bulk_relationships.html.erb
Adds an entity matching mode to the bulk upload tool
> Bulkupload - Entity Matching Mode

- app/helpers/entities_helper.rb
- app/utility/sorted_links.rb
- spec/utility/sorted_links_spec.rb
+  add a couple of tests for SortedLinks
> Fix membership display bug on profile page

- app/assets/javascripts/pages/bulkAdd.js
- app/views/tools/bulk_relationships.html.erb
- improved styles for match box
- better scrolling
- clicking on profile link no longer causes a selection to be made
- adds a 'nothing found' message
> Tweaks and Improvements to the bulk upload tool

- app/assets/stylesheets/styles/entities.scss
- app/controllers/entities_controller.rb
- app/models/entity.rb
- app/models/relationship.rb
- app/validators/relationship_validator.rb
- app/views/entities/_actions.html.erb
- app/views/lists/members.html.erb
- app/views/shared/_bootstrap_nav_menu.html.erb
- spec/controllers/entities_controller_spec.rb
- spec/models/entity_spec.rb
- spec/validators/relationship_validator_spec.rb
- spec/views/entities/_actions.html.erb_spec.rb
- spec/views/entities/show.html.erb_spec.rb
> Replace Symfony Delete Entity Route with rails version

- app/models/concerns/tagable.rb
- app/models/entity.rb
- app/models/list.rb
- app/models/relationship.rb
- app/models/tag.rb
- app/models/tagging.rb
- config/tags.yml
- db/migrate/20170802165123_create_taggings.rb
- db/schema.rb
- db/structure.sql
- spec/models/concerns/tagable_spec.rb
- spec/models/entity_spec.rb
- spec/models/tag_spec.rb
- spec/models/tagging_spec.rb
- spec/testdata/tags.yml
resolves #245 and completes acceptance criteria listed there (repeated below):
* given an entity/relationship/list "x" i should be able to apply the "oil" tag using either a name or id for the tag
* given i have already applied to "oil" tag to x i can ask for x's tags and see a list that includes "oil"
* given i have already applied the "oil" tag to x, if i apply it again and ask for x's tags, i will only see "oil" once
____
**Tagging an Entity:**
**Tagging a Relationship:**
**Tagging a List:**
> Tag entity, relationship, or list in console

- app/models/link.rb
- app/models/relationship.rb
- spec/factories/relationship.rb
- spec/models/link_spec.rb
> [#209] Display degree & education relationship info on profile page

- app/models/concerns/tagable.rb
- app/models/tagging.rb
- spec/models/concerns/tagable_spec.rb
- spec/models/tagging_spec.rb
- spec/views/entities/sidebar/_sidebar.html.erb_spec.rb
+ make tagable a polymorphic association
+ fix sidebar tests by skipping callback
> [#226] add Tagging callback to update associated tagable timestamp

- .travis.yml
- app/assets/javascripts/common/tags.js
- app/assets/stylesheets/styles/tags.scss
- app/controllers/concerns/tagable_controller.rb
- app/controllers/entities_controller.rb
- app/helpers/entities_helper.rb
- app/models/concerns/tagable.rb
- app/models/tag.rb
- app/views/entities/_sidebar.html.erb
- app/views/entities/sidebar/_source_links.html.erb
- config/environments/test.rb
- config/routes.rb
- config/tags.yml
- spec/controllers/entities_controller_spec.rb
- spec/javascripts/common/tags.spec.js
- spec/javascripts/helpers/jasmine-jquery.js
- spec/javascripts/pages/political.spec.js
- spec/models/concerns/tagable_spec.rb
- spec/models/tag_spec.rb
- spec/requests/tagging_spec.rb
- spec/views/entities/sidebar/_sidebar.html.erb_spec.rb
> Add/remove tags on entity page (impl.)

- app/models/sf_guard_user_profile.rb
- app/validators/signup_reason_validator.rb
- app/views/users/registrations/new.html.erb
- spec/controllers/users_registrations_controller_spec.rb
- spec/factories/sf_guard_user_profile.rb
- spec/models/sf_guard_user_profile_spec.rb
This presents models from being saved in the database as well as giving UI hints to the user when they try to submit the form without writing enough information
> Require users to fill out the 'about you' text input when signing up

- db/migrate/20170829211602_add_index_on_whodunnit_to_versions.rb
- db/schema.rb
- db/structure.sql
This will make finding edits for an individual user faster.
**Before the index**, it has to search  all the rows:
**after the indexing** the searching is faster:
> [#244] index column whodunnit on table versions

- app/views/relationships/_header.html.erb
- app/views/relationships/_sources.html.erb
- spec/features/viewing_relationship_page_spec.rb
+ add features spec for relationships page
> [#214] source links on relationship page open in new tab

- app/models/relationship.rb
- app/utility/ls_date.rb
- spec/models/relationship_spec.rb
- spec/utility/ls_date_spec.rb
- spec/views/entities/_link.html.erb_spec.rb
+ Invalid LsDate  raises a custom error
+ Relationship#display_date_range handles the error
+ refactored display_date_range tests
> [#217] handle error when relationship date string is invalid

- app/assets/stylesheets/styles/relationships.scss
- app/controllers/relationships_controller.rb
- app/helpers/tags_helper.rb
- app/views/relationships/_actions.html.erb
- app/views/relationships/_sources.html.erb
- app/views/relationships/show.html.erb
- config/routes.rb
- spec/controllers/relationships_controller_spec.rb
- spec/requests/tagging_spec.rb
- spec/support/helpers.rb
- spec/views/relationships/show.html.erb_spec.rb
+ created new view helper: TagsHelper
resolves #230 and #231
> [#230|#231] display and edit tags on relationship page

- app/views/users/registrations/new.html.erb
> [#294] Change newsletter wording & set default newsletter checkbox status to checked

- app/helpers/lists_helper.rb
- app/views/lists/_header.html.erb
- spec/views/lists/_header.html.erb_spec.rb
> [#235] Tags always appear on right on list page

- app/assets/stylesheets/styles/tags.scss
- app/controllers/tags_controller.rb
- app/models/concerns/tagable.rb
- app/models/entity.rb
- app/models/relationship.rb
- app/models/tag.rb
- app/views/tags/show.html.erb
- config/routes.rb
- lib/scripts/load_tags.rb
- spec/factories/tagging.rb
- spec/features/tags_spec.rb
- spec/models/concerns/tagable_spec.rb
- spec/models/tag_spec.rb
- spec/models/tagging_spec.rb
resolves #234 
___________________
screengrab:
i tried to make a gif out of using the pagination bars and clicking on the links to prove they work, but i couldn't get `peek` to work. so just trust me: you can click on the pagination bars and the links! they work! :)
> Tag homepage

- app/assets/stylesheets/styles/tags.scss
- app/controllers/tags_controller.rb
- app/helpers/tags_helper.rb
- app/models/tag.rb
- app/views/tags/show.html.erb
- spec/features/tags_spec.rb
- spec/models/concerns/tagable_spec.rb
- spec/models/tag_spec.rb
resolves #305 
uses some gnarly SQL. see ``` tag.rb ``` for comments.
> Sort tagged entities by relationship

- app/models/concerns/network_analysis.rb
augment #353 to optimize performance (and complete #335)
* BUG: giving tab for Robert Rubin took > 20sec to load w/o caching
* CAUSE: indexing on `relationships` table makes it slower to query
than `links` (it also has more fields)
* FIX: refactor `#connected_id_hashes_for` and helpers to query
`links` table -> query now takes <6 sec (bad but acceptable)
* **side-effect:** our queries now vary the direction of a link based on
what kind of link we are examining and whether we are inspecting the
first or second hop. this is more intuitive to think about than
varying the position of `entity1_id` or `entity2_id` (also we now
have self-documenting names about first and second hops which did
not exist before)
> [#335|cleanup] refactor NetworkAnalysis to use Links not Relationships

- app/assets/javascripts/pages/bulkAdd.js
- app/controllers/relationships_controller.rb
- app/views/tools/bulk_relationships.html.erb
There's a notes column. And it's _optional_:
> Add notes column to bulk add tool

- app/assets/stylesheets/styles/tags.scss
- app/helpers/entities_helper.rb
- app/helpers/tags_helper.rb
- app/models/concerns/network_analysis.rb
- app/views/entities/_connections.html.erb
- app/views/entities/_giving.html.erb
- app/views/entities/_interlocks.html.erb
- app/views/entities/_sidebar.html.erb
- app/views/lists/_tags.html.erb
- spec/features/entity_page_spec.rb
- spec/models/concerns/network_analysis_spec.rb
- spec/support/network_analysis_helper.rb
resovles #336 
--- 
* inlclude "hops-centric" reformatting of `network_analysis` module
* TODO: extract helper class for network analysis queries
> Giving tab on org profile uses rails

- lib/task-helpers/query.rb
- lib/tasks/query.rake
* added task helper module -- Query
> rake task: retrieve ny state donations for all list members

- app/assets/javascripts/pages/referenceWidget.js
This should help ease the transition to the new UI.
> Show default list of suggestions in existing reference widget

- app/helpers/tags_helper.rb
- spec/helpers/tags_helper_spec.rb
> [#391] handle nil editors on edits tab on tag homepage

- spec/utility/entity_merger_spec.rb
> [#384] add spec for merging entities

- app/views/entities/edit.html.erb
> adds instructional text to entity dates

- app/assets/javascripts/pages/bulkAdd.js
After downloading a sample csv, the first row is filled out with sample data. 
Resolves #388
> Add example row to bulk add relationship sample csv

- Gemfile
- Gemfile.lock
- app/assets/javascripts/pages/NyMatchDonations.js
- app/controllers/nys_controller.rb
- app/models/ny_match.rb
- config/routes.rb
- spec/controllers/nys_controller_spec.rb
- spec/javascripts/pages/NyMatchDonations.spec.js
- spec/models/ny_match_spec.rb
- spec/rails_helper.rb
- spec/requests/nys_spec.rb
- spec/support/helpers.rb
- spec/support/request_macros.rb
Allows unmatching of ny state donations
resolves #399
> Unmatch ny donations

- app/assets/stylesheets/documents.scss
- app/controllers/concerns/params_helper.rb
- app/controllers/documents_controller.rb
- app/models/document.rb
- app/views/documents/edit.html.erb
- app/views/entities/references.html.erb
- app/views/relationships/_sources.html.erb
- config/routes.rb
- spec/controllers/documents_controller_spec.rb
- spec/features/document_spec.rb
- spec/models/document_spec.rb
> Edit document

- app/controllers/merge_controller.rb
- app/mailers/notification_mailer.rb
- app/views/entities/_actions.html.erb
- app/views/entities/_sidebar.html.erb
- app/views/entities/show.html.erb
- app/views/merge/_merge_request_form.html.erb
- app/views/merge/_similar_entities_table.html.erb
- app/views/notification_mailer/merge_request_email.text.erb
- app/views/shared/_notice_or_alert.html.erb
- spec/features/merging_spec.rb
- spec/mailers/notification_mailer_spec.rb
- spec/views/entities/show.html.erb_spec.rb
- spec/views/entities/sidebar/_sidebar.html.erb_spec.rb
Resolves #442 and fulfills its acceptance criteria.
_________
[Approving an Email-generated Merge Request](https://vimeo.com/248409944)
> Request merge by email

- app/controllers/deletion_requests_controller.rb
- app/mailers/notification_mailer.rb
- app/views/deletion_requests/_report.html.erb
- app/views/deletion_requests/_request_form.html.erb
- app/views/deletion_requests/_review_form.html.erb
- app/views/deletion_requests/new.html.erb
- app/views/entities/_actions.html.erb
- app/views/notification_mailer/deletion_request_email.text.erb
- config/routes.rb
- spec/controllers/deletion_requests_controller_spec.rb
- spec/features/entity_deletion_spec.rb
- spec/mailers/notification_mailer_spec.rb
- spec/views/entities/_actions.html.erb_spec.rb
- spec/views/entities/show.html.erb_spec.rb
Resolves #445 and fulfills all acceptance criteria accept the one noted in the **NOTES** section below, which has been moved to a subsequent card.
_______
[User flow for requesting and approving an entity deletion](https://vimeo.com/249036709)
* this is intended to be merged after (and rebased onto) #458 and #459 
* it does not include relationships, as noted in [this comment to 445](https://github.com/public-accountability/littlesis-rails/issues/444#issuecomment-354387652), but instead defers that work to #460
> Request deletion by email

- app/helpers/home_helper.rb
- app/views/home/dashboard.html.erb
- spec/factories/network_maps.rb
- spec/features/dashboard_spec.rb
- spec/helpers/home_helper_spec.rb
- spec/models/network_map_spec.rb
> show default image for maps that are missing thumbnails

- .gitignore
- .travis.yml
- app/controllers/maps_controller.rb
- config/thinking_sphinx.yml
- spec/controllers/maps_controller_spec.rb
- spec/rails_helper.rb
- spec/requests/maps_spec.rb
- spec/support/sphinx_test_helper.rb
These include our **first** tests which run sphinx!
> Fix #364 - unescaped sphinx queries 

- .rubocop.yml
- data/cmp_matches.yml
- lib/cmp.rb
- lib/cmp/cmp_org.rb
- lib/cmp/entity_match.rb
- lib/tasks/cmp.rake
- spec/lib/cmp_org_spec.rb
- spec/lib/cmp_spec.rb
This is a working importer for CMP orgs, although we won't run it on production just yet.
> Import CMP Orgs

- app/models/person.rb
- db/migrate/20180129193750_add_nationality_to_person.rb
- db/schema.rb
- lib/cmp.rb
- lib/cmp/cmp_entity_importer.rb
- lib/cmp/cmp_org.rb
- lib/cmp/cmp_person.rb
- lib/cmp/cmp_relationship.rb
- lib/cmp/datasets.rb
- lib/cmp/person_sheet.rb
- lib/cmp/relationship_sheet.rb
- lib/tasks/cmp.rake
- spec/lib/cmp_org_spec.rb
- spec/lib/cmp_person_spec.rb
- spec/lib/cmp_relationship_spec.rb
- spec/models/entity_spec.rb
- spec/models/person_spec.rb
- spec/requests/api_spec.rb
major changes:
- add new field to person 'Nationality'
- rake task to process cmp person /relationship data
- module `Cmp::Datasets` containing (lazily loaded) constants of each dataset
> Generate spreadsheet of people with potential matches for CMP data

- app/controllers/application_controller.rb
- app/controllers/chat_controller.rb
- app/controllers/entities_controller.rb
- spec/requests/chat_spec.rb
- spec/requests/entities_spec.rb
- spec/support/request_macros.rb
* restricted users can no longer access chat
* restricted users can no longer update entities
> Prevent restricted users from editing entities and accessing chat

- app/assets/stylesheets/styles/deletion-requests.scss
- app/assets/stylesheets/styles/user-requests.scss
- app/controllers/deletion_requests_controller.rb
- app/controllers/merge_controller.rb
- app/models/deletion_request.rb
- app/models/merge_request.rb
- app/models/user.rb
- app/models/user_request.rb
- app/views/deletion_requests/_report.html.erb
- app/views/deletion_requests/_request_form.html.erb
- app/views/merge/_merge_request_form.html.erb
- app/views/user_requests/_description.html.erb
- db/migrate/20180327200500_add_justification_to_user_request.rb
- db/schema.rb
- spec/factories/deletion_requests.rb
- spec/factories/merge_requests.rb
- spec/factories/user_requests.rb
- spec/features/entity_deletion_spec.rb
- spec/features/merging_spec.rb
- spec/models/user_request_spec.rb
- spec/models/user_spec.rb
> Justify merge and deletion requests

- app/assets/javascripts/pages/bulkAdd.js
- app/assets/javascripts/utility.js
- app/controllers/application_controller.rb
- app/controllers/relationships_controller.rb
- app/helpers/application_helper.rb
- app/helpers/relationships_helper.rb
- app/helpers/tools_helper.rb
- app/models/relationship.rb
- app/models/trans.rb
- app/views/relationships/_description_fields_display.html.erb
- app/views/relationships/_description_fields_entity_row.html.erb
- app/views/relationships/_reverse_link.js.erb
- app/views/relationships/bulk_add.html.erb
- app/views/relationships/edit.html.erb
- spec/controllers/relationships_controller_bulk_add_spec.rb
- spec/controllers/relationships_controller_spec.rb
- spec/factories/relationship.rb
- spec/helpers/tools_helper_spec.rb
- spec/models/relationship_spec.rb
- spec/requests/relationships_spec.rb
- spec/support/request_macros.rb
> Reversing Memership Relationships

- app/models/concerns/soft_delete.rb
- app/models/tag.rb
- app/utility/links_group.rb
- app/utility/sorted_links.rb
- app/views/entities/_actions.html.erb
- app/views/entities/show.html.erb
- app/views/home/dashboard.html.erb
- app/views/relationships/_actions.html.erb
- app/views/relationships/_header.html.erb
- config/application.rb
- spec/features/entity_page_spec.rb
- spec/models/tag_spec.rb
- spec/views/entities/match_donations.html.erb_spec.rb
- spec/views/entities/political.html.erb_spec.rb
- spec/views/entities/show.html.erb_spec.rb
- fix flag link on relationship page (closes #597 )
- remove whitespace from tags (closes #534 )
- fix scope/method confusion in `SoftDelete` (closes #526 )
- update help links on dashoard and redirect legacy urls (closes #582 )
- donor relationships are sorted correctly (closes #598 )
- remove social media buttons from profile pages (closes #601 )
> Various bug fixes

- app/controllers/relationships_controller.rb
- app/models/relationship.rb
- spec/controllers/relationships_controller_spec.rb
- spec/models/relationship_spec.rb
- spec/requests/relationships_spec.rb
> set entity/related last user id correctly when relationship is deleted

- .travis.yml
- Gemfile
- Gemfile.lock
- app/assets/javascripts/common/api.js
- app/assets/javascripts/pages/entity.js
- app/assets/stylesheets/styles/datatable.scss
- app/assets/stylesheets/styles/entities.scss
- app/controllers/entities_controller.rb
- app/presenters/entity_version_presenter.rb
- app/presenters/version_presenter.rb
- app/views/entities/_editable_blurb.html.erb
- app/views/entities/_header.html.erb
- app/views/entities/show.html.erb
- spec/features/entity_page_spec.rb
- spec/javascripts/common/api.spec.js
- spec/javascripts/pages/entity.spec.js
- spec/requests/entities_spec.rb
- spec/views/entities/show.html.erb_spec.rb
+ working javascript tests on travis!
> edit blurb in place

- .rubocop.yml
- app/controllers/application_controller.rb
- app/controllers/entities_controller.rb
- app/controllers/relationships_controller.rb
- app/models/user_permission.rb
- app/utility/permissions.rb
- app/utility/routes.rb
- app/views/entities/_actions.html.erb
- app/views/relationships/_actions.html.erb
- config/routes.rb
- spec/controllers/entities_controller_spec.rb
- spec/models/user_permission_spec.rb
- spec/requests/entities_spec.rb
- spec/requests/relationships_spec.rb
- spec/utility/permissions_spec.rb
- spec/utility/routes_spec.rb
- spec/views/entities/_actions.html.erb_spec.rb
- spec/views/relationships/show.html.erb_spec.rb
closes #169. see that issue for details on when an entity or relationship can be deleted.
> Allow users to delete entities and relationships that they've created 

- app/models/entity.rb
- app/models/relationship.rb
- app/models/user.rb
- app/validators/user_name_validator.rb
- app/views/entities/_new_entity_form.html.erb
- app/views/users/registrations/new.html.erb
- spec/factories/users.rb
- spec/models/entity_spec.rb
- spec/models/user_spec.rb
- spec/validators/user_name_validator_spec.rb
fixes #485 
fixes #363 
fixes #514
> Validations for blurb and usernarme

- app/assets/javascripts/pages/bulkAdd.js
> [#256] reset entity match queue after deleting row

- app/assets/stylesheets/styles/entities.scss
- app/helpers/entities_helper.rb
- app/views/entities/_no_relationships.html.erb
- app/views/entities/_relationships.html.erb
- spec/features/entity_page_spec.rb
closes #123 
FYI: will likely have to clear the rails cache
> Show message on profile page without relationships

- app/controllers/maps_controller.rb
- app/models/network_map.rb
- spec/controllers/maps_controller_spec.rb
- spec/models/network_map_spec.rb
>  add "clone" to title of cloned maps

- app/assets/stylesheets/styles/home.scss
- app/views/home/dashboard.html.erb
> Remove gap from dashboard

- app/helpers/relationships_helper.rb
- app/models/relationship.rb
- app/views/relationships/edit.html.erb
- spec/models/relationship_spec.rb
Server and client validation of description fields
closes #622 
closes #620
> Relationship description fields validation

- app/jobs/update_entity_network_map_collections_job.rb
- app/models/entity.rb
- app/models/network_map.rb
- app/utility/entity_network_map_collection.rb
- app/views/entities/_sidebar.html.erb
- app/views/entities/show.html.erb
- lib/tasks/maps.rake
- spec/features/entity_page_spec.rb
- spec/jobs/update_entity_network_map_collections_job_spec.rb
- spec/models/entity_spec.rb
- spec/models/network_map_spec.rb
- spec/utility/entity_network_map_collection_spec.rb
> Add oligrapher section to sidebar of profile page

- app/controllers/home_controller.rb
- app/views/home/dashboard.html.erb
- spec/controllers/home_controller_spec.rb
- spec/features/dashboard_spec.rb
closes #650 
closes #688 
closes #690
> Dashboard Improvements: add pager for lists, remove groups, add link to explore tags

- .travis.yml
- app/controllers/home_controller.rb
- app/presenters/user_maps_presenter.rb
- app/views/home/maps.html.erb
- config/database.travis.yml
- config/environments/test.rb
- db/migrate/20180813162356_create_network_map_link_function.rb
- db/schema.rb
- db/structure.sql
- lib/query.rb
- lib/sql/network_map_link.sql
- lib/tasks/mysql.rake
- spec/lib/network_map_sql_spec.rb
- spec/presenters/user_maps_presenter_spec.rb
- vendor/assets/javascripts/jquery.dataTables.js
* use datatables on frontend
* add first custom sql function `network_map_link`
> add searchable table of maps created by user at home/maps

- app/controllers/home_controller.rb
- app/jobs/newsletter_signup_job.rb
- app/utility/action_network.rb
- config/routes.rb
- spec/controllers/home_controller_spec.rb
- spec/jobs/newsletter_signup_job_spec.rb
- spec/requests/home_spec.rb
>> POST /home/pai_signup/press
> ActionNetwork newsletter signup - press list

- app/controllers/home_controller.rb
- app/presenters/user_lists_presenter.rb
- app/utility/permissions.rb
- app/views/home/lists.html.erb
- spec/presenters/user_lists_presenter_spec.rb
> new "your lists" page using DataTables

- Gemfile
- Gemfile.lock
- app/models/image.rb
- app/models/network_map.rb
- app/utility/s3.rb
- lib/tasks/images.rake
* **correctly** update object metadata
* rake task to fix public access, content-type, and cache-control for all images
* remove unused RMagik Gem
* Improve code in `Image ` and `S3`
* add gem HTTParty
> Fix various issues with our S3 image system

- app/assets/stylesheets/styles/relationships.scss
- app/views/entities/_link.html.erb
- app/views/entities/_relationships.html.erb
- app/views/home/_oligrapher.html.erb
> remove top line on 'see all' section of profile pages

- app/indices/ny_filer_index.rb
- app/models/unmatched_ny_filer.rb
- app/utility/datatable.rb
**require running rake rs:rebuild**
> only show unmatched filers while searching on entity match table

- app/utility/entity_merger.rb
- spec/utility/entity_merger_spec.rb
> [#727] don't merge external links of the same type

- app/assets/javascripts/pages/addRelationship.js
- app/models/relationship_category.rb
- app/validators/relationship_validator.rb
- db/seeds.rb
- spec/validators/relationship_validator_spec.rb
resolves #735 
run this on the server:
``` RelationshipCategory.find(3).update!(entity2_requirements: 'Org') ```
> Ensure entity2 is an Org for Membership relationships

- app/controllers/users_controller.rb
- app/models/user.rb
- app/validators/user_name_validator.rb
- app/views/users/registrations/new.html.erb
- config/routes.rb
- spec/controllers/users_controller_spec.rb
- spec/models/user_spec.rb
- spec/requests/users_spec.rb
- spec/validators/user_name_validator_spec.rb
> client-side validation of username uniqueness

- app/models/network_map.rb
- lib/tasks/maps.rake
- spec/models/network_map_spec.rb
> Hide "Untitled Maps" from sidebar

- app/models/network_map.rb
- spec/models/network_map_spec.rb
> Soft delete network maps

- app/controllers/dashboard_bulletins_controller.rb
- app/helpers/application_helper.rb
- app/models/dashboard_bulletin.rb
- app/validators/css_color_validator.rb
- app/views/dashboard_bulletins/_bulletin.html.erb
- app/views/dashboard_bulletins/_form.html.erb
- db/migrate/20181204170212_add_color_to_dashboard_bulletin.rb
- db/schema.rb
- db/structure.sql
- spec/factories/dashboard_bulletins.rb
- spec/features/dashboard_bulletins_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/models/dashboard_bulletin_spec.rb
- spec/validators/css_color_validator_spec.rb
> Add colors to dashboard bulletins

- db/migrate/20181210213242_change_versions_object_column_size.rb
- db/schema.rb
- db/structure.sql
> change column `versions`.`object` to longtext

- app/controllers/maps_controller.rb
- app/models/network_map.rb
- app/models/sf_guard_user.rb
- app/models/user.rb
- db/migrate/20181212195611_convert_network_map_user_id_to_use_rails_id.rb
- db/schema.rb
- db/structure.sql
- spec/features/dashboard_spec.rb
- spec/features/maps_spec.rb
- spec/features/user_page_spec.rb
- spec/models/network_map_spec.rb
- spec/presenters/user_maps_presenter_spec.rb
- spec/requests/maps_spec.rb
- spec/support/request_macros.rb
> Refactor NetworkMap to use rails user ids

- app/models/concerns/user_edits.rb
- app/models/edited_entity.rb
- app/presenters/entity_last_editor_presenter.rb
- app/utility/entity_history.rb
- app/utility/permissions.rb
- app/views/edits/index.html.erb
- lib/scripts/create_example_user.rb
- spec/features/edits_spec.rb
- spec/features/entity_page_spec.rb
- spec/models/concerns/user_edits_spec.rb
- spec/presenters/entity_last_editor_presenter_spec.rb
- spec/utility/permissions_spec.rb
- spec/views/entities/show.html.erb_spec.rb
> Use versions and EditedEntity to display entity edits

- app/controllers/images_controller.rb
- app/models/image_deletion_request.rb
- app/views/entities/images.html.erb
- app/views/images/deletion_request.html.erb
- spec/requests/images_spec.rb
> Improve image deletion request review page

- app/models/concerns/user_edits.rb
- app/models/edited_entity.rb
- app/utility/entity_history.rb
- app/views/home/dashboard.html.erb
- app/views/users/show.html.erb
- spec/models/concerns/user_edits_spec.rb
- spec/models/edited_entity_spec.rb
* don't use find_by_sql - includes works now
* remove `Collections`
* Should properly handle deleted and merged entities
> Refactor Edited Entity - fix problem with merged and deleted entities

- app/models/network_map.rb
- app/utility/oligrapher_graph_data.rb
- app/utility/oligrapher_graph_data_image_fixer.rb
- app/views/maps/story_map.html.erb
- lib/tasks/maps.rake
- spec/controllers/maps_controller_spec.rb
- spec/models/network_map_spec.rb
- spec/utility/oligrapher_graph_data_image_fixer_spec.rb
> Fix broken images on map

- app/presenters/relationship_label.rb
- spec/presenters/relationship_label_spec.rb
> add amount to link description for transaction relationships

- app/assets/stylesheets/styles/entities.scss
- app/views/shared/_bootstrap_nav_menu.html.erb
- app/views/tags/index.html.erb
- app/views/tags/show.html.erb
fixes #846 
fixes #834 
fixes #738
> Minor css changes, fix public-accountability url, remove groups from nav bar, add page title ot tag pages

- app/controllers/maps_controller.rb
- app/controllers/nys_controller.rb
- app/controllers/search_controller.rb
- app/models/concerns/entity_search.rb
- app/utility/datatable.rb
- app/utility/ls_search.rb
- spec/models/concerns/entity_search_spec.rb
- spec/utility/ls_search_spec.rb
> Allow exact searches with double quotes

- app/assets/javascripts/common/api.js
- app/assets/javascripts/nys.js
- app/assets/javascripts/pages/addRelationship.js
- app/assets/javascripts/pages/bulkAdd.js
- app/controllers/search_controller.rb
- app/services/entity_search_service.rb
- app/views/shared/_add_entity_js.html.erb
- spec/controllers/search_controller_spec.rb
- spec/services/entity_search_service_spec.rb
* use "primary_ext" instead of "primary_name"
* replace param "no_summary" with return_type=simple
> refactor /search/entity

- app/controllers/external_datasets_controller.rb
- app/javascript/packs/entity_matcher.jsx
- app/javascript/packs/entity_matcher/EntityMatcherUI.jsx
- app/javascript/packs/entity_matcher/actions.js
- app/javascript/packs/entity_matcher/components/DatasetItemFooter.jsx
- app/models/external_dataset.rb
- app/models/external_datasets/iapd_datum.rb
- spec/models/external_datasets/iapd_datum_spec.rb
> Entity Matcher: go to next adivsor

- app/controllers/external_datasets_controller.rb
- app/javascript/packs/entity_matcher/components/NewEntityForm.jsx
- app/utility/exceptions.rb
- spec/controllers/external_datasets_controller_spec.rb
- spec/javascripts/entity_matcher/NewEntityForm.test.jsx
- spec/requests/external_datasets_spec.rb
- yarn.lock
> form to create new entities

- app/models/note.rb
- app/models/note_entity.rb
- app/models/note_group.rb
- app/models/note_list.rb
- app/models/note_relationship.rb
- app/models/note_user.rb
- app/models/sf_guard_user.rb
- db/migrate/20190514141806_drop_note_tables.rb
- db/schema.rb
- db/structure.sql
- spec/factories/list.rb
> Remove notes table and models

- app/javascript/packs/entity_matcher/components/DatasetItemInfo.jsx
- app/models/business.rb
- app/models/external_datasets/iapd_datum.rb
- db/migrate/20190521205445_add_aum_to_business.rb
- db/schema.rb
- db/structure.sql
- spec/factories/businesses.rb
- spec/models/business_spec.rb
- spec/models/external_datasets/iapd_datum_spec.rb
> Add name of adviser to entity matcher owner flow

- app/services/external_dataset_service/iapd.rb
- spec/services/external_dataset_service_spec.rb
> add aum while matching iapd advisors

- db/schema.rb
- db/structure.sql
- spec/models/user_spec.rb
> remove column chatid from users

- app/models/relationship.rb
- app/utility/ls_date.rb
- app/validators/date_validator.rb
- spec/models/relationship_spec.rb
- spec/utility/ls_date_spec.rb
- spec/validators/date_validator_spec.rb
> Relationship date validation

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/pages/referenceModal.js
- app/assets/stylesheets/main.scss
- app/views/entities/add_relationship.html.erb
> remove bootstrap datepicker

- app/models/link.rb
- app/models/relationship.rb
- app/presenters/relationship_label.rb
- app/utility/sorted_links.rb
- app/views/entities/_link.html.erb
- spec/models/relationship_spec.rb
- spec/presenters/relationship_label_spec.rb
- spec/views/entities/_link.html.erb_spec.rb
> Add asterisk if relationship contains a note

- app/controllers/entities_controller.rb
- app/models/image.rb
- app/views/entities/new_image.html.erb
- db/migrate/20190604175919_remove_title_from_image.rb
- db/schema.rb
- db/structure.sql
- spec/factories/image.rb
- spec/features/images_spec.rb
- spec/models/entity_deleting_spec.rb
- spec/models/image_spec.rb
- spec/requests/entities_spec.rb
Instead the column `caption` is used instead
resolves #951
> remove column "title" from image

- app/models/image.rb
- spec/features/images_spec.rb
- spec/models/image_spec.rb
- spec/requests/entities_spec.rb
> feature image after creating when entity has no other featured image

- .rubocop.yml
- app/javascript/packs/entity_matcher/components/ConfirmationPage.jsx
- app/models/external_datasets/iapd_datum.rb
- app/services/iapd_relationship_service.rb
- spec/javascripts/entity_matcher/ConfirmationPage.test.jsx
- spec/services/iapd_relationship_service_spec.rb
>  Only add people owners to the iapd owner queue

- app/models/external_datasets/iapd_datum.rb
- lib/tasks/iapd.rake
> iapd rake tasks to update advisor and owner queues

- app/controllers/maps_controller.rb
- app/helpers/network_maps_helper.rb
- spec/features/maps_spec.rb
- spec/helpers/network_maps_helper_spec.rb
> allow user to declare oligrapher version in url param

- app/helpers/entities_helper.rb
> re-arrange the order of sections on profile page

- .travis.yml
> mariadb 10.3

- app/models/image.rb
- spec/models/image_spec.rb
> handle uploads of images with spaces in filename

- app/queries/entity_connections_query.rb
- app/views/api/index.html.erb
- spec/queries/entity_connections_query_spec.rb
- relationship_id
- relationship_category_id
> api /connections route includes two additional fields

- app/assets/stylesheets/styles/datatable.scss
- app/controllers/lists_controller.rb
- app/presenters/version_presenter.rb
- app/utility/ls_date.rb
- app/views/lists/index.html.erb
- app/views/merge/_merge_request_description.html.erb
- app/views/merge/redundant_merge_review.html.erb
- app/views/user_requests/_description.html.erb
- config/locales/en.yml
- spec/features/entity_deletion_spec.rb
- spec/features/list_spec.rb
- spec/features/merging_spec.rb
- spec/presenters/entity_version_presenter_spec.rb
- spec/requests/api_spec.rb
- spec/utility/ls_date_spec.rb
> Sort lists by created_at

- app/models/link.rb
- spec/factories/link.rb
- spec/models/link_spec.rb
> Show percent stake on link description for ownership relationships

- app/views/lists/references.html.erb
- spec/requests/lists_spec.rb
> use url if document does not have a name on list sources page

- app/mailers/application_mailer.rb
- app/mailers/notification_mailer.rb
- config/lilsis.yml.sample
- spec/mailers/notification_mailer_spec.rb
> Use default email for all notification emails

- app/views/relationships/edit.html.erb
- app/views/shared/editing/_edit_references_panel.html.erb
> edit relationship page: validity msg encourages use of references

- app/models/concerns/political.rb
- app/views/entities/political.html.erb
- spec/models/entity_spec.rb
- spec/views/entities/political.html.erb_spec.rb
> 185 add no donations message to political tab

- app/models/entity.rb
- app/models/merge_request.rb
- app/services/pending_entity_request_resolver.rb
- spec/models/entity_deleting_spec.rb
- spec/services/pending_entity_request_resolver_spec.rb
- spec/utility/entity_merger_spec.rb
resolves #753
+ clean up entity_merge_spec
> resolve merge requests after an entity has been deleted 

- .rubocop.yml
- app/assets/stylesheets/styles/entities.scss
- app/controllers/images_controller.rb
- app/utility/image_file.rb
- app/views/entities/_image_table_row.html.erb
- app/views/entities/images.html.erb
- config/routes.rb
- spec/controllers/images_controller_spec.rb
- spec/features/images_spec.rb
- spec/requests/images_spec.rb
> Edit image caption

- app/controllers/oligrapher_controller.rb
- app/utility/oligrapher.rb
- config/routes.rb
- spec/controllers/oligrapher_controller_spec.rb
- spec/requests/oligrapher_request_spec.rb
- spec/utility/oligrapher_spec.rb
Created oligrapher/find_connections json endpoint to return entities connected to a given entity
> Oligrapher find connections

- app/models/list_entity.rb
- spec/utility/entity_merger_spec.rb
> alows list entities to be transfered from deleted lists

- app/controllers/application_controller.rb
- app/controllers/concerns/maps_helper.rb
- app/controllers/maps_controller.rb
- app/controllers/oligrapher_controller.rb
- app/models/network_map.rb
- app/models/user.rb
- app/services/oligrapher_lock_service.rb
- app/utility/oligrapher.rb
- app/views/layouts/oligrapher3.html.erb
- app/views/oligrapher/oligrapher.html.erb
- config/routes.rb
- db/migrate/20200511192227_add_settings_to_network_map.rb
- db/schema.rb
- db/structure.sql
- spec/controllers/oligrapher_controller_spec.rb
- spec/models/network_map_spec.rb
- spec/requests/maps_spec.rb
- spec/requests/oligrapher_request_spec.rb
- spec/services/oligrapher_lock_service_spec.rb
Changes to management of NetworkMap editors
NetworkMap settings stored as serialized json in new database column
> Oligrapher fixes

- app/controllers/tags_controller.rb
- spec/requests/tagging_spec.rb
> Fix tag request form

- app/assets/javascripts/common/api.js
- app/assets/javascripts/pages/addRelationship.js
- app/controllers/search_controller.rb
- app/javascript/packs/tags/EntityTagSearch.jsx
- app/models/entity.rb
- app/services/entity_search_service.rb
- app/views/entities/_new_entity_form.html.erb
- app/views/lists/members.html.erb
- app/views/shared/_add_entity_js.html.erb
- spec/controllers/search_controller_spec.rb
- spec/factories/extension_definitions.rb
- spec/models/entity_spec.rb
- spec/requests/api_spec.rb
- spec/services/entity_search_service_spec.rb
Resolves #74
It seems that a sort that prioritises parents has already been done at some point. This just adds a column that states if an entity is a parent.
> parent corps in relationship search

- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- app/views/users/registrations/edit.html.erb
- spec/features/user_settings_spec.rb
> Allow users to update their own usernames

- app/assets/javascripts/application.js
- app/assets/javascripts/pages/entity.js
- app/assets/stylesheets/application.css.scss
- app/controllers/entities_controller.rb
- app/controllers/lists_controller.rb
- app/models/list.rb
- app/models/list_entity.rb
- app/views/entities/_sidebar.html.erb
- config/routes.rb
- package.json
- spec/controllers/entities_controller_spec.rb
- spec/controllers/lists_controller_spec.rb
- spec/models/list_spec.rb
- spec/requests/lists_spec.rb
- vendor/assets/javascripts/select2.full.min.js
- vendor/assets/stylesheets/select2.min.css
- yarn.lock
> Add an entity to lists from its profile page

- app/models/relationship.rb
- app/presenters/relationship_label.rb
- app/utility/links_group.rb
- spec/models/relationship_spec.rb
- spec/utility/links_group_spec.rb
- spec/views/entities/_link.html.erb_spec.rb
> Prioritize recent or current relationships on entity profile

- app/assets/javascripts/common/tooltips.js
- app/views/entities/_connections.html.erb
- app/views/entities/_relationships.html.erb
> Entity blurb on interlocks links

- app/models/concerns/referenceable.rb
- app/models/list.rb
- app/views/lists/new.html.erb
- spec/controllers/lists_controller_spec.rb
- spec/features/list_spec.rb
- spec/models/concerns/referenceable_spec.rb
- spec/requests/lists_spec.rb
> Allow lists without sources

- app/assets/javascripts/common/clipboard.js
- app/assets/stylesheets/main.scss
- app/assets/stylesheets/styles/permission_passes.scss
- app/controllers/permission_passes_controller.rb
- app/javascript/packs/application.js
- app/models/permission_pass.rb
- app/models/user.rb
- app/views/admin/home.html.erb
- app/views/permission_passes/_form.html.erb
- app/views/permission_passes/edit.html.erb
- app/views/permission_passes/index.html.erb
- app/views/permission_passes/new.html.erb
- config/routes.rb
- db/migrate/20200702145236_create_permission_passes.rb
- db/schema.rb
- db/structure.sql
- package.json
- spec/controllers/permission_passes_controller_spec.rb
- spec/factories/permission_passes.rb
- spec/factories/users.rb
- spec/features/admin_pages_spec.rb
- spec/features/permission_pass_spec.rb
- spec/models/edited_entity_spec.rb
- spec/models/permission_pass_spec.rb
- spec/support/capybara_helpers.rb
- yarn.lock
> Permission passes

- config/initializers/session_store.rb
- db/migrate/20200625162604_drop_sessions_table.rb
- db/schema.rb
- db/structure.sql
> Switch session store from database to Redis

- app/javascript/packs/common/api.js
- app/javascript/packs/components/list_bulk_entity_adder.js
- app/views/lists/new_entity_associations.html.erb
- config/webpack/environment.js
Note: the tests for bulk-adding entities to lists effectively cover this already.
We should probably use this approach for other "common" modules such as utility.
> Move API JS to webpacker

- app/views/search/_cantfind.html.erb
> Add missing column

- app/helpers/application_helper.rb
> Tell browsers not to autofill the honeypot

- app/controllers/home_controller.rb
- app/controllers/tags_controller.rb
- app/controllers/users/registrations_controller.rb
- app/helpers/application_helper.rb
- app/views/admin/tags.html.erb
- app/views/application/_flash.html.erb
- app/views/entities/images.html.erb
- app/views/home/_contact_header.html.erb
- app/views/home/dashboard.html.erb
- app/views/layouts/application.html.erb
- app/views/users/admin.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- spec/controllers/home_controller_spec.rb
- spec/features/signup_spec.rb
> Sitewide flash infrastructure

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/styles/forms.scss
- app/javascript/controllers/username_validation_controller.js
- app/javascript/packs/application.js
- app/views/application/_math_captcha.html.erb
- app/views/users/registrations/new.html.erb
- config/routes.rb
- package.json
- spec/controllers/users_controller_spec.rb
- spec/features/js/user_registration_form_spec.rb
- spec/requests/users_spec.rb
- yarn.lock
Making the JS here unobtrusive.
I think we should apply the same general approach to all JS form validations: use Parsley as the framework, with our own customizations where appropriate.
> Refactor new user form js

- app/assets/stylesheets/styles/edits.scss
- app/assets/stylesheets/styles/lists.scss
- app/assets/stylesheets/styles/maps.scss
- app/controllers/lists_controller.rb
- app/helpers/entities_helper.rb
- app/helpers/lists_helper.rb
- app/helpers/network_maps_helper.rb
- app/indices/list_index.rb
- app/models/entity.rb
- app/models/list.rb
- app/presenters/user_navmenu_presenter.rb
- app/services/search_service.rb
- app/views/entities/_sidebar.html.erb
- app/views/home/lists.html.erb
- app/views/lists/_index_header.html.erb
- app/views/lists/edit.html.erb
- app/views/lists/index.html.erb
- app/views/maps/_table.html.erb
- spec/controllers/lists_controller_spec.rb
- spec/features/entity_page_spec.rb
- spec/features/js/featured_list_admin_spec.rb
- spec/features/maps_spec.rb
- spec/helpers/network_maps_helper_spec.rb
- spec/models/entity_spec.rb
- spec/services/search_service_spec.rb
> Featured lists

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/styles/relationships.scss
- app/controllers/relationships_controller.rb
- app/utility/links_group.rb
- app/views/entities/_link.html.erb
- app/views/entities/show.html.erb
- app/views/relationships/_actions.html.erb
- db/migrate/20210524101935_add_is_featured_column_to_relationships.rb
- spec/features/featured_relationship_admin_spec.rb
- spec/utility/links_group_spec.rb
> Featured relationships

- app/utility/sorted_links.rb
- spec/utility/sorted_links_spec.rb
Just started this. Could do with a thorough rationalisation. Related to #1441
> Refactor sorted links

- app/models/entity.rb
- app/models/image.rb
- app/models/user.rb
- app/utility/image_file.rb
- app/utility/utility.rb
- db/migrate/20211208180233_remove_has_square_from_images.rb
- db/structure.sql
- lib/tasks/maps.rake
- spec/models/image_spec.rb
- convert original files to jpeg
- follow redirects
- remove legacy has_square
> image fixes

- Dockerfile
- config/littlesis.yml
- update Dockerfile
- fix redis urls
> fix redis url

- .gitignore
- DEVELOPMENT.md
- app/utility/list_datatable.rb
- config/development.sphinx.conf
- config/docker/pg-setup-database.sh
- config/docker/postgresql.conf
- **Increasing List Interlock threshold.  Fixes #1671.**
> Increasing List Interlock threshold

- app/views/layouts/application.html.erb
- config/docker/nginx.conf
- spec/features/maps_spec.rb
- **remove cache headers from oligrapher assets**
- **Adding analytics JS snippet. Addresses #1677**
> Add analytics JS snippet

- Gemfile
- app/models/position.rb
- spec/models/position_spec.rb
- spec/requests/updating_board_membership_status_spec.rb
> fix recalculate subcategory callback

- app/views/entities/add_relationship/_results.html.erb
> fix spelling error

- config/application.rb
> Adding missing class to the permitted_classes list

- app/helpers/application_helper.rb
> Fixing metatag misspelling

- app/assets/stylesheets/styles/_home.scss
> Changing text color of Dashboard bulletins headers

- app/assets/stylesheets/styles/_home.scss
- app/controllers/lists_controller.rb
- app/queries/lists_index_query.rb
- config/development.sphinx.conf
#1712
The or logic is based on https://freelancing-gods.com/thinking-sphinx/v5/common_issues#or_attributes
> including current user's private lists in index

- app/models/external_link.rb
> allow x.com for twitter regex

- app/models/entity.rb
> show all regions, not arbitrary 'primary' (first) one

- app/controllers/references_controller.rb
- app/views/lists/references.html.erb
> check if referenceable is editable by current user

- app/views/entities/_edit_profile.html.erb
- app/views/entities/edit.html.erb
> Readding start and end date to org edit form.

- app/assets/stylesheets/profile.scss
> Increasing z-index for select2 list on entity edit modal

- app/assets/stylesheets/styles/_relationships.scss
- app/views/relationships/_edit_relationship.html.erb
> Fixing curreny and goods/services input width.

- app/views/search/basic.html.erb
> Show the "Add It" button whenever on search page (if logged in)

- app/views/shared/_nav_menu.html.erb
> Setting navigation logo link to /home path rather than domain root.
