public-accountability/littlesis-rails

.travis.yml
README.md
config/database.travis.yml
config/lilsis.yml.sample
db/structure.sql

Using schema.rb to create the testing database fails. The workaround is to use structure.sql for the testing environment.
After changing the schema and migrating the test database run:
``` RAILS_ENV=test bundle exec rake db:structure:dump ```
which will update structure.sql (otherwise the automated tests will fail)

Travis CI configuration

---

app/controllers/application_controller.rb
app/controllers/entities_controller.rb
app/controllers/users/confirmations_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/utility/ip_blocker.rb
app/views/users/admin.html.erb
config/lilsis.yml.sample
config/routes.rb
db/migrate/20170706142752_add_is_restricted_to_user.rb
db/schema.rb
db/structure.sql
lib/exceptions.rb
spec/controllers/entities_controller_spec.rb
spec/controllers/users_confirmations_controllers_spec.rb
spec/controllers/users_controller_spec.rb
spec/factories/sf_guard_user_profile.rb
spec/factories/users.rb
spec/features/users_admin_spec.rb
spec/models/user_spec.rb
spec/rails_helper.rb
spec/support/controller_macros.rb
spec/support/helpers.rb
spec/utility/ip_blocker_spec.rb
spec/views/home/flag.html.erb_spec.rb

Allows users to be set to 'restricted' via the /users/admin page.
Being *restricted* allows you to access the site, but you cannot do anything that requires permissions. This is essentially the same as being a user without any permissions.
Adds a new configuration "restricted_ips" -- a list of ip addresses (or ranges), where if a user signs up from one of those addresses it automatically makes their account restricted. 
resolves #192

Restricted Users + Fight Spam

---

app/assets/stylesheets/styles/lists.scss
app/controllers/lists_controller.rb
app/indices/list_index.rb
app/models/list.rb
app/views/lists/_form.html.erb
app/views/lists/_header.html.erb
app/views/lists/_list_actions.html.erb
app/views/lists/index.html.erb
app/views/lists/new.html.erb
db/migrate/20170626212039_add_short_description_to_lists.rb
db/schema.rb
db/structure.sql
spec/models/list_spec.rb
spec/views/lists/new.html.erb_spec.rb

Let me know how you like the display choices for short description vs [full] description. On the show page for a list, I have both; the index of lists shows long description only if a short description doesn't exist (which is the case for basically all lists, currently).

adds "short description" field to lists

---

app/assets/stylesheets/styles/lists.scss
app/helpers/lists_helper.rb
app/views/lists/_header.html.erb
app/views/lists/_tags.html.erb
spec/models/tag_spec.rb
spec/testdata/tags.yml
spec/views/lists/_header.html.erb_spec.rb

There are two different layouts depending on the number of tags. For lists
with 2 or fewer tags, they will appear in line with the list
title. For lists with more than 2 tags, they will appear in their own
column to the right of tags.
resolves #235

[#235] Show tags on list page

---

app/views/shared/_bootstrap_nav_menu.html.erb

[#278] remove /press from navbar

---

app/assets/stylesheets/styles/lists.scss
app/views/lists/_settings.html.erb

This is _exactly_ a popover but I think it gets the point across:
resolves #272

[#272] Add list access rules guidance to edit list page

---

Gemfile
Gemfile.lock
app/controllers/users/registrations_controller.rb
app/views/users/registrations/new.html.erb
config/initializers/recaptcha.rb
config/lilsis.yml.sample

This replaces the custom math problem with google's recaptcha:
I *kind of* cheated and pushed this to the server via git branch switching to totally make sure that it works live and it does:

[#293] Replace math problem with recaptcha on /join

---

app/controllers/search_controller.rb
app/models/concerns/entity_search.rb
app/models/tag.rb
app/views/search/basic.html.erb
config/routes.rb
spec/factories/groups.rb
spec/factories/list.rb
spec/factories/tag.rb
spec/models/entity_spec.rb
spec/models/tag_spec.rb
spec/support/tag_spec_helper.rb
spec/views/search/basic.html.erb_spec.rb

resolves #297 
Adds tags section to search results:
dev notes:
- Did some testing and refactoring of SearchController, but there's still more to be done.
-  it looks for the presence of a tag name in the search string. for instance if you search for "real estate companies" it will find the real estate tag. however, it does not do any fancy fuzzy matching or search within the tag description field -- perhaps that's something to add later on?

Add tags to search results

---

app/controllers/tags_controller.rb
app/mailers/notification_mailer.rb
app/views/notification_mailer/tag_request_email.text.erb
app/views/tags/tag_request.html.erb
config/routes.rb
spec/controllers/tags_controller_spec.rb
spec/features/request_a_tag_spec.rb
spec/mailers/notification_mailer_spec.rb

This creates a new page where users can request new tags:
after submitting the request it sends the user to their dashboard:
The requests arrive via email just like the contact us and flag requests.
resolves #299

Request a tag page

---

app/assets/stylesheets/styles/tags.scss
app/controllers/tags_controller.rb
app/helpers/tags_helper.rb
app/views/entities/_sidebar.html.erb
app/views/lists/_tags.html.erb
app/views/tags/index.html.erb
app/views/tags/show.html.erb
config/routes.rb
spec/controllers/tags_controller_spec.rb
spec/features/tags_spec.rb
spec/rails_helper.rb
spec/support/feature_macros.rb

resolves #232 
* for consistency, opted to add clickable links to all view-mode tags throughout site (as this PR introduced them on overview page)
* reverted to slower feature spec setup to avoid non-determinstic state collisions with other part of suite
_____
**NOTE:** my screenshot program does not show the hand pointer. these links have hand pointers (not arrow pointers) when being hovered over.
clickable links on the overview page:
link to overview page from tag homepage (plus more stylish "red tag" look in header):
clickable links on the entity page:
clickable links on the list page:
clickable links on the relationship page:

static tag overview page

---

lib/task-helpers/bulk_tagger.rb
lib/task-helpers/bulk_tagging.rb
lib/tasks/tags.rake
spec/lib/bulk_tagging_spec.rb

Adds two new rake tasks:
> tags:entity[file]
> tags:list[file]
If you provide a path to a csv file it will process the file and tag the entities or lists.
**csv headers for entity:**
```
| entity_url | tags | tag_all_related |
```
**csv headers for list:**
```
| list_url | tags | tag_all_in_list |
```
tags can be any number of tags separated by a space. i.e.: ``` georgia fracking finance ```. Capitalization doesn't matter, but the tags must already exist in the system. 
if _tag_all_related_ is selected, it will tag all entities that the entity is related to. if _tag_all_in_list_ is picked, it will tag all entities in that list. 
Resolves #296

Scripted bulk tagging

---

app/models/concerns/tagable.rb
app/models/entity.rb
app/models/relationship.rb
lib/exceptions.rb
spec/controllers/entities_controller_spec.rb
spec/models/concerns/tagable_spec.rb
spec/models/entity_deleting_spec.rb
spec/models/entity_spec.rb
spec/models/relationship_spec.rb

This adds a methods``` restore! ``` to both _Entity_ and _Relationship_.
If called on deleted models, it will un-delete them, including re-creating or restoring links, tags, and any other associations that existed. 
By default it won't restore an entities relationships, but if you can optionally  restore the relatioships:
``` entity#restore!(true) ```
#241 concerns just tags, although this pull requests concerns restoring all entity associations incuding tags

Restoring deleted entities and relationships

---

app/controllers/users/registrations_controller.rb
app/controllers/users_controller.rb
app/views/users/success.html.erb
spec/controllers/users_controller_spec.rb

resolves #250 
**Current Page:**
Perhaps later we can expand that page with more instructions or details?

Direct users to page with instructions after they join

---

app/models/alias.rb
app/models/entity.rb
spec/models/alias_spec.rb
spec/models/entity_spec.rb

resolves #292 
Already existing entities can be fixed using this code:
``` rb
Entity.where("name REGEXP '^[ ].*'").each do |e|
e.update_column(:name, e.name.strip)
end
Entity.where("name REGEXP '.*[ ]$'").each do |e|
e.update_column(:name, e.name.strip)
end
```

Trim whitespace from name for entities and aliases

---

app/assets/stylesheets/styles/tags.scss
app/controllers/tags_controller.rb
app/models/concerns/tagable.rb
app/models/tag.rb
app/views/tags/show.html.erb
config/routes.rb
spec/controllers/tags_controller_spec.rb
spec/factories/tagging.rb
spec/features/tags_spec.rb
spec/models/concerns/tagable_spec.rb
spec/models/tag_spec.rb

resolves #306
______
**entities tab**
**empty state**
**lists tab**
**relationships tab**
______
* use `tags/:id/:tag_category` route to infer tag list from params
* introduce `has_many through` associations between `Tag` and any `Tagable` instance
* use these associations to hand `Tagable` instances to homepage view instead of  `Tagging` instances, eliminate `#group_taggings_by_class`
* introduce convention of `tag_category` (always pluralized, downcased version of tagable's class name)
* replace `Tagable#TAGABLE_CLASSES` with `Tagable.classes` (only accessible on `Tagable` module itself, *not* classes that include it)
* add `Tagable.categories` method that enumerates a tagable category (lowercase plural string) for each tagable class
* use `Tagable.categories` to safely/extensibly place …

Tag homepage grouped by tags

---

app/assets/stylesheets/styles/tags.scss
app/controllers/tags_controller.rb
app/models/tag.rb
app/views/tags/_tagable_list.html.erb
app/views/tags/show.html.erb
lib/scripts/load_tags.rb
spec/features/tags_spec.rb
spec/models/tag_spec.rb

resolves #307 
____
**Entity tab with an empty sublist:**
**Entity tab with pagination:**
__________
* show sublists by subtypes for entities (in a manner that is extensible
to any future tagable class that might have subtypes)
* show subheaders if there are sublists
* infer sublists from a @tagable_subtypes instance variable
* set @tagable_subtypes to `[nil]` if there are no subtypes so we may
avoid an `if/else` branch and simply always render the `_tagable_list`
partial in all scenarios, with appropriate locals plugged in based on
value of @tagable_subtypes
* modify `LoadTags#load` to tag N entities of subtype `Person` and `Org`
* cleanup feature specs for a tagable list
@aepyornis: open to suggestions on optimizing the SQL here.
all i can vouch for is that it is correct...

Entity tab on tag homepage grouped by type

---

app/controllers/tags_controller.rb
app/helpers/tags_helper.rb
app/models/tag.rb
app/views/tags/_header.html.erb
app/views/tags/edits.html.erb
app/views/tags/show.html.erb
config/routes.rb
spec/controllers/tags_controller_spec.rb
spec/features/tags_spec.rb
spec/helpers/tags_helper_spec.rb
spec/models/tag_spec.rb
spec/support/tagging_helper.rb
spec/views/tags/_header.html.erb_spec.rb

One idea I though of doing for this but didn't : adding last_user_id to Tagging to keep track of who added the tag...but perhaps it's not essential?
There's likely many style improvements to be made. Happy to get advice on that.

Recent edits by tag

---

app/helpers/tags_helper.rb
app/models/concerns/pagination.rb
app/models/tag.rb
spec/models/tag_spec.rb

resolves #309 
____________________
* extract generic `Pagination` module, observe its contract in `tag.rb`
* use dynamic method delegation in `#tagables_for_homepage`
* try to establish conventions for helpers for `#tagables_for_homepage`
* use custom sql query for list sorting (as with entity sorting)
* introduce pagination test at model level
* mark helpers for `recent_edits_for_homepage` as private

Lists tab on homepage sorted by number of list members

---

app/controllers/users/registrations_controller.rb
app/views/shared/_bootstrap_nav_menu.html.erb
app/views/users/registrations/new.html.erb
lib/tasks/legacy.rake
spec/features/dashboard_spec.rb
spec/models/tag_spec.rb

Entirely removing networks breaks symfony, so we'll have to wait until we finish migrating to rails to finish removing networks.
Until then, this removes the link to networks from the nav bar and from the join page.

Remove networks from join page and from nav bar

---

app/helpers/entities_helper.rb
app/models/concerns/interlocks.rb
app/views/entities/_interlocks.html.erb
spec/factories/entities.rb
spec/factories/relationship.rb
spec/features/entity_page_spec.rb
spec/models/concerns/interlocks_spec.rb
spec/support/interlocks_helper.rb

resolves #334 
----
New page, same as the old page:
* replace `person` and `orgs` keys with `connected_entity` and `connecting_entities`
* add helper functions to abstract over entity & category ids
* `#root_entity_id_key` switches on `primary_ext` to determine the hash key we should use to query an interlock tree's root entity -- (either `:entity1_id` or `:entity2_id`)
* `#connecting_entity_id_key` switches on `primary_ext` to determine the hash key we should use to query an interlock tree's first-hop nodes (ie: connecting entities) -- (either `:entity1_id or :entity2_id)
* use generalized key names for `connected_id` has in `_interlocks` partial (eliminating `person` and `orgs` as in `interlocks.rb`
* create `#entity_interlocks_header` helper to dynamically generate title and subtitle …

Org interlocks tab uses rails

---

app/helpers/relationships_helper.rb
app/views/relationships/_description_fields_display.html.erb
app/views/relationships/_description_fields_entity_row.html.erb
spec/factories/relationship.rb
spec/features/edit_relationship_page_spec.rb
spec/support/feature_macros.rb

"Parent" now appears before "Child" on the edit relationship page:
This resolves #362 and #259 
Also see https://github.com/public-accountability/littlesis-browser-addon/issues/20 for related changes to the browser extension

[#362] switch position of child/parent order on relationship edit page

---

app/helpers/tags_helper.rb
app/models/concerns/tagable.rb
app/models/entity.rb
app/models/tag.rb
app/models/tagging.rb
app/views/tags/edits.html.erb
db/migrate/20171010214602_add_last_user_id_to_tagging.rb
db/schema.rb
db/structure.sql
lib/task-helpers/bulk_tagger.rb
spec/features/entity_page_spec.rb
spec/features/tags_spec.rb
spec/helpers/tags_helper_spec.rb
spec/lib/bulk_tagging_spec.rb
spec/models/concerns/tagable_spec.rb
spec/models/entity_deleting_spec.rb
spec/models/entity_spec.rb
spec/models/tag_spec.rb
spec/models/tagging_spec.rb
spec/views/entities/sidebar/_sidebar.html.erb_spec.rb

resolves #238 
and supplements #326, which was discovered to be incomplete at last show & tell
--------------
* pass (sf_guard) user id to `Tagable#tag`
* use AR associations to give `Tagging` a `last_user` method
* refactor `#recent_edits` SQL query to find `last_user_id` for both
`tag_added` and `tagable_updated` events, store as `editor_id`
* use `editor_id` to lookup user in (renamed) `#editors_by_id` helper
* use new `tags_helper` method to format username or `System`
* simplify `Time` column to omit (1) "Edited", (2) omit username
* rename helper methods to `#recent_edits` to reflect the shape of the data they return, and flesh out descriptions of their return (pseudo)types
* discard intermediary id fields from hash returned by `#recent_edits` (build a new hash that only has values …

Add `edited by` column to tags edit page

---

app/controllers/users/registrations_controller.rb
app/models/sf_guard_user_profile.rb
app/views/users/registrations/new.html.erb
spec/features/signup_spec.rb

resolves #357 
If the SfGuardUserProfile had an invalid field, the error message
wouldn't appear in devise user messages, causing the account
sign up to fail without providing any visual indication to the user.
Errors message are now handled in the controller, and the models are saved in a
transaction to ensure that SfGuardUserProfiles are never persisted
without the user model also being saved.

[#357] Validate username and wrap user models in a transaction

---

app/models/concerns/soft_delete.rb
app/models/entity.rb
app/models/os_committee.rb
app/models/os_match.rb
app/models/relationship.rb
db/migrate/20171031152314_remove_reference_id_from_os_matches.rb
db/schema.rb
db/structure.sql
spec/factories/os_donations.rb
spec/javascripts/pages/referenceWidget.spec.js
spec/models/document_spec.rb
spec/models/os_committee_spec.rb
spec/models/os_match_spec.rb
spec/models/relationship_spec.rb

Fixes a few remaining issues with our new references system:
- Removes reference_id from OsMatch and have os match use the new reference system
- store document_ids after a relationship is soft_deleted, so relationship references are restorable
- refactor OsMatch tests
- fix the non-working interaction test

OsMatch References Refactor + other small reference-related changes

---

app/controllers/entities_controller.rb
app/helpers/tags_helper.rb
app/models/concerns/similar_entities.rb
app/views/entities/_sidebar.html.erb
app/views/lists/_header.html.erb
app/views/relationships/show.html.erb
app/views/shared/_bootstrap_nav_menu.html.erb
spec/controllers/entities_controller_spec.rb
spec/features/dashboard_spec.rb
spec/features/entity_page_spec.rb
spec/features/list_spec.rb
spec/features/viewing_relationship_page_spec.rb
spec/views/entities/show.html.erb_spec.rb
spec/views/entities/sidebar/_sidebar.html.erb_spec.rb

resolves #345 
This pull request makes tags visible for all. It also adds 'tags' to the 'explore' section of the nav bar.

Make tags publically visible

---

app/assets/stylesheets/styles/home.scss
app/controllers/users/registrations_controller.rb
app/views/users/registrations/new.html.erb
db/migrate/20171109155832_add_location_to_sf_guard_user_profile.rb
db/migrate/20171109174122_add_map_the_power_to_user.rb
db/schema.rb
db/structure.sql
spec/features/signup_spec.rb
spec/models/sf_guard_user_profile_spec.rb
spec/models/user_spec.rb

Resolves #377 
Makes the following changes to the join page:
- Removes the data summary and replaces it with the map the power logo
- changes the 'get involved' text
- adds location field
- adds interested in map the power check box
- other minor style changes
two changes to our models:
- add string field 'location' to sf_guard_user_profile
- add boolean field 'map_the_power' to user
____________________________________________

Join page improvements

---

app/assets/javascripts/pages/bulkTable.js

(caused rails precompile to fail, b/c not parseable in ES5)

BUGFIX: eliminate arrow function in `bulkTable.js`

---

app/assets/javascripts/pages/bulkTable.js
app/assets/javascripts/utility.js
spec/javascripts/common/bulkTable.spec.js
spec/javascripts/common/utility.spec.js

resolves #417
_______
* create and use `utility#appendSpinner` (which leveraged nice spinner styles in `assets/stylesheets/base/spin.css`
* in `bulkTable`: 
* set spinner state in state tree, only show spinners during `render` calls if corresponding boolen flag is set 
* no need to call #remove, since if there is no spinner it will not be rendered
* do not toggle spinner state directly on DOM (only indirectly through Flux-type unidirectional data flow: event handler -> state -> render -> DOM)

Bulk list tool: show spinners during upload and submission

---

app/controllers/application_controller.rb
app/controllers/entities_controller.rb
app/models/entity.rb
lib/exceptions.rb
spec/controllers/edits_controller_spec.rb
spec/controllers/entities_controller_spec.rb
spec/features/entity_page_spec.rb
spec/models/entity_spec.rb

resolves #420 
___
[see video here](https://vimeo.com/246551860)
* introduce `Entity#resolve_entities`, use to recursively resolve an entity from chain of merged entities (or return itself)
* introduce `MergedEntityError` exception
* use the combination of these to recursively redirect merged entities or return a 404 if entity or merged enity has been deleted
* additionally. refactor `EntityController#set_entity_with_eager_loading` to delegate to `ApplicationController#set_entity` for DRY-ness and single-point-of-truth re: merges, etc...

Redirect merged entities

---

app/controllers/users/confirmations_controller.rb
app/controllers/users_controller.rb
app/mailers/notification_mailer.rb
app/views/notification_mailer/signup_email.html.erb
spec/controllers/users_confirmations_controllers_spec.rb
spec/controllers/users_controller_spec.rb
spec/features/user_page_spec.rb
spec/mailers/notification_mailer_spec.rb

resolves #376 and resolves #394 
add information -- Email, Location, and if they are interested to map the power -- to the notification email sent to admins.  It also skips sending those email if the user signed up from a restricted IP.
It also prevents user pages from being visible for restricted users (which will hopefully reduce the incentive for spammy signups)

User signup notification email

---

app/models/cmp_entity.rb
app/models/entity.rb
app/utility/ls_hash.rb
db/migrate/20180123192048_create_cmp_entities.rb
db/migrate/20180124213412_add_entity_extension_elite_consensus.rb
db/schema.rb
db/seeds.rb
lib/cmp.rb
lib/cmp/cmp_entity.rb
lib/cmp/cmp_entity_importer.rb
lib/cmp/cmp_org.rb
lib/cmp/cmp_person.rb
lib/cmp/entity_match.rb
lib/cmp/org_sheet.rb
lib/cmp/org_type.rb
spec/factories/cmp_entities.rb
spec/helpers/entities_helper_spec.rb
spec/lib/cmp_org_spec.rb
spec/lib/cmp_spec.rb
spec/models/cmp_entity_spec.rb
spec/models/extension_definition_spec.rb
spec/utility/ls_hash_spec.rb

This is largely a work-in-progress pull request, although the org importer is nearly ready.
Major changes:
- Adds bew entity extension _elite consensus_ (resolves #503)
- New utility class ` LsHash `
- New model  `CmpEntity` which joins cmp ids with LittleSis entity ids

Add Elite Consensus + CMP importer work in progress

---

app/views/shared/_bootstrap_nav_menu.html.erb
spec/features/dashboard_spec.rb

- removed Beginners and Advanced help
- renamed "Search Help Pages" to "Help"

[#506] update navbar links under 'Help'

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/styles/home.scss
app/controllers/home_controller.rb
app/controllers/users/confirmations_controller.rb
app/jobs/application_job.rb
app/jobs/newsletter_signup_job.rb
app/models/user.rb
app/utility/action_network.rb
app/views/home/_newsletter_signup_form.html.erb
app/views/home/_newsletter_thankyou.html.erb
app/views/home/index.html.erb
config/lilsis.yml.sample
config/routes.rb
spec/controllers/home_controller_spec.rb
spec/controllers/users_confirmations_controllers_spec.rb
spec/factories/users.rb
spec/features/homepage_spec.rb
spec/jobs/newsletter_signup_job_spec.rb
spec/models/user_spec.rb
spec/testdata/action_network_api_info.json
spec/utility/action_network_spec.rb

- use action network api to signup users (if they request it) to our mailing it
- create the app's first `ApplicationJob` to send api requests
- replace mailchimp form on front page
- clean up HomeController and specs
closes #533 
closes #538

Intergrate with ActionNetwork

---

.rubocop.yml
app/controllers/references_controller.rb
app/models/concerns/referenceable.rb
app/models/document.rb
app/utility/ls_date.rb
spec/models/document_spec.rb
spec/requests/references_spec.rb
spec/utility/ls_date_spec.rb

- `Document` will first convert the provided publication date using LsDate
- `LsDate.convert` turns blank strings into nil
- linting for LsDate and document specs
fixes #547

Fix bug when adding new references from entity references display page

---

Gemfile
Gemfile.lock
app/models/person.rb
app/utility/entity_matcher.rb
app/utility/entity_matcher/evaluation.rb
app/utility/entity_matcher/evaluation_result.rb
app/utility/entity_matcher/evaluator.rb
app/utility/entity_matcher/test_case.rb
app/utility/name_similarity.rb
app/utility/type_check.rb
lib/cmp/cmp_person.rb
lib/tasks/cmp.rake
spec/models/person_spec.rb
spec/rails_helper.rb
spec/support/helpers.rb
spec/utility/entity_matcher_spec.rb
spec/utility/name_similarity_spec.rb
spec/utility/type_check_spec.rb

This adds a complete way to compare two entity and/or test entities.
after comparing it produces a result object with 10 boolean flags:
- same_last_name
- same_first_name
- same_middle_middle
- same_prefix
- same_suffix
- mismatched_suffix
- similar_last_name
- similar_first_name
- common_relationship
- blurb_keyword
next step is to rank these comparisons!
adds one new gem, [text](https://github.com/threedaymonk/text).
creates two helper class/modules that might be useful in other parts of the code base:
- `TypeCheck` -- a simple way to check the types of arguments
- `NameSimilarity` - determines if names are similar

Entity resolution work in progress #2

---

app/assets/stylesheets/base/helpers.scss
app/assets/stylesheets/styles/edits.scss
app/assets/stylesheets/styles/maps.scss
app/assets/stylesheets/styles/users.scss
app/controllers/maps_controller.rb
app/controllers/users_controller.rb
app/helpers/network_maps_helper.rb
app/indices/network_map_index.rb
app/models/network_map.rb
app/presenters/user_presenter.rb
app/views/maps/_table.html.erb
app/views/maps/index.html.erb
app/views/maps/search.html.erb
app/views/maps/story_map.html.erb
app/views/users/_maps_table.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/controllers/maps_controller_spec.rb
spec/features/maps_spec.rb
spec/features/user_page_spec.rb
spec/presenters/user_presenter_spec.rb
spec/requests/maps_spec.rb
spec/support/request_macros.rb

This changes how featured maps are handled. only admins can feature/unfeature a map. They do so by click a star on the maps index page.
changes:
going to */maps* now redirects to */maps/featured*
to view all maps you can either click the button 'All' or go to /maps/all
Private maps are now hidden from admins
closes #540 
closes #541 
closes #543

Featured Maps

---

app/models/cmp_entity.rb
app/utility/entity_matcher.rb
app/utility/entity_matcher/evaluation_result.rb
app/utility/entity_matcher/evaluation_result_set.rb
app/utility/entity_matcher/search.rb
app/utility/entity_matcher/test_case.rb
app/utility/org_name.rb
data/cmp_matches.yml
lib/cmp.rb
lib/cmp/cmp_entity_importer.rb
lib/cmp/cmp_org.rb
lib/cmp/cmp_person.rb
lib/cmp/cmp_relationship.rb
lib/cmp/datasets.rb
lib/cmp/entity_match.rb
lib/query.rb
lib/tasks/cmp.rake
spec/lib/cmp_org_spec.rb
spec/lib/cmp_person_spec.rb
spec/lib/cmp_spec.rb
spec/support/helpers.rb
spec/utility/entity_matcher_spec.rb
spec/utility/org_name_spec.rb

- ` EntityMatcher::EvaluationResult ` has method #automatch? which determined if it matches enough criteria to be auto-matched. 
- when importing, the edits are attributed to a CMP user
- ` OrgName.format ` formats an organizational name
-  EntityMatcher  is used instead of specific cmp matcher: Cmp::EntityMatch

Update cmp org importer, determine if found entities can be automatched, add cmp people rake tasks

---

app/assets/stylesheets/base/globals.scss
app/assets/stylesheets/base/helpers.scss
app/assets/stylesheets/styles/edits.scss
app/views/edits/entity.html.erb
spec/features/entity_history_page_spec.rb

add title and notice to entity history pages:
resolves #537 
___________

add title, message to history pages

---

app/controllers/home_controller.rb
app/controllers/lists_controller.rb
app/controllers/search_controller.rb
app/helpers/entities_helper.rb
app/helpers/lists_helper.rb
app/indices/entity_index.rb
app/indices/list_index.rb
app/indices/note_index.rb
app/models/entity.rb
app/models/group.rb
app/models/list.rb
app/models/list_entity.rb
app/models/note.rb
app/models/note_network.rb
app/models/user.rb
app/utility/relationships_datatable.rb
app/views/lists/_list_actions.html.erb
db/migrate/20180424164740_drop_is_network_from_ls_list.rb
db/migrate/20180424165127_remove_network_lists_and_list_entities.rb
db/migrate/20180424181848_drop_table_note_networks.rb
db/schema.rb
db/seeds.rb
spec/factories/list.rb
spec/models/entity_spec.rb
spec/models/list_spec.rb

removes entirely the network functionality from lists, including removing the list entities from our database.

Remove networks

---

app/controllers/application_controller.rb
app/controllers/dashboard_bulletins_controller.rb
app/models/dashboard_bulletin.rb
app/views/admin/home.html.erb
app/views/dashboard_bulletins/_bulletin.html.erb
app/views/dashboard_bulletins/_bulletins.html.erb
app/views/dashboard_bulletins/_form.html.erb
app/views/dashboard_bulletins/edit.html.erb
app/views/dashboard_bulletins/index.html.erb
app/views/dashboard_bulletins/new.html.erb
app/views/home/_list_alerts.html.erb
app/views/home/dashboard.html.erb
config/routes.rb
db/migrate/20180522142905_create_dashboard_bulletins.rb
db/schema.rb
spec/controllers/dashboard_bulletins_controller_spec.rb
spec/factories/dashboard_bulletins.rb
spec/features/admin_pages_spec.rb
spec/features/dashboard_bulletins_spec.rb
spec/features/dashboard_spec.rb
spec/models/dashboard_bulletin_spec.rb
spec/support/feature_macros.rb

Replace existing hard-coded panels on dashboard with editable bulletins. Admins can compose bulletins in markdown.  Bulletins can easily be edited and deleted. 
viewing list of current bulletins (admin-only): 
add a new bulletin (admin-only):
displayed on dashboard (all users):

Editable Dashboard bulletins

---

app/controllers/home_controller.rb
app/views/home/_dashboard_map.html.erb
app/views/home/dashboard.html.erb
config/locales/en.yml
spec/controllers/home_controller_spec.rb
spec/features/dashboard_spec.rb

only show at most 18 maps on the dashboard. If user has more than 18 maps, a paginator will appear.
resolves #631

[#631] paginate maps on dashboard

---

app/controllers/application_controller.rb
app/controllers/entities_controller.rb
app/controllers/lists_controller.rb
app/models/user.rb
app/utility/exceptions.rb
spec/controllers/entities_controller_spec.rb
spec/controllers/lists_controller_spec.rb
spec/factories/users.rb
spec/features/adding_a_list_spec.rb
spec/features/new_entity_spec.rb
spec/models/user_spec.rb
spec/support/list_helpers.rb

closes #764 
This  adds a probation period for all accounts. After confirming their email address, users must now wait 10 whole minutes until they can create or edit lists or entities.
This should hopefully prevent some spam lists and entities from being creating by spam users.

don't let new users create entities or lists he first 10 minutes that the account is active

---

app/assets/javascripts/oligrapher-dev.js
app/assets/javascripts/oligrapher-dev.js.map
app/controllers/maps_controller.rb
app/helpers/network_maps_helper.rb
app/models/network_map.rb
app/views/layouts/embedded_oligrapher.html.erb
app/views/layouts/fullscreen.html.erb
app/views/layouts/oligrapher.html.erb
app/views/maps/embedded.html.erb
app/views/maps/embedded_v2.html.erb
app/views/maps/story_map.html.erb
config/lilsis.yml.sample
config/routes.rb
spec/controllers/maps_controller_spec.rb
spec/features/maps_spec.rb
spec/helpers/network_maps_helper_spec.rb
spec/models/network_map_spec.rb

- No longer compile oligrapher with sprockets
- oligrapher is now versioned based on the git tag and served via our web server (outside of rails)
- paths to oligrapher: ` /js/oligrapher/oligrpaher-VERSION.js ` and ` /js/oligrapher/oligrapher_littlesis_bridge-VERSION.js `
- dev version of oligrapher is removed and instead support for source maps have been added

Oligrapher assets overhaul

---

app/controllers/api/api_controller.rb
app/controllers/users/passwords_controller.rb
spec/requests/api_spec.rb

resolves #837 
It don't solve the situation of  non-signed in users (aka anyone normally browsing our site) to be able to access the api. Perhaps down the line we might want to use our own AP on public pages, but that's not not needed at the moment.

signed in users can make API requests without a token

---

app/services/external_dataset_service/iapd.rb
spec/models/edited_entity_spec.rb
spec/services/external_dataset_service_spec.rb

- handle case where matching with entity that already has a crd
number
- check that no other entity has claimed the crd number already

improve ExternalDatasetService::Iapd#validate_match

---

app/controllers/entities_controller.rb
app/models/concerns/entity_extensions.rb
app/views/entities/edit.html.erb
spec/controllers/entities_controller_spec.rb
spec/factories/entities.rb
spec/features/edit_entity_spec.rb
spec/features/new_entity_spec.rb

Implements #501. 
I have added only the fields specified in #501, but we could also add `revenue` from the `org` object if that is useful.

Editable business fields

---

app/utility/list_datatable.rb
app/views/lists/_datatable.html.erb

On ranked lists, unranked entities should come last

---

app/utility/oligrapher.rb
spec/factories/entities.rb
spec/requests/oligrapher_request_spec.rb
spec/utility/oligrapher_spec.rb

so that entity descriptions can be shown in Oligrapher's NodeTool search results
(I don't know why i named this branch oligrapher-find-node-images instead of oligrapher-find-node-descriptions)

add descriptions to results of oligrapher/find_nodes endpoint

---

app/assets/javascripts/pages/entity.js
app/controllers/entities_controller.rb
app/views/entities/_new_entity_form.html.erb
config/routes.rb
spec/controllers/entities_controller_spec.rb
spec/models/entity_spec.rb

Calls the API for entity validation on form input `blur` and presents the result with the same formatting we would use for a server-side validation.
This is a general-purpose method and will work for anything that can be validated server-side. In the present case, we specify only the `name` attribute for validation.

Client side entity name validation

---

app/queries/entity_connections_query.rb
config/environments/development.rb
spec/queries/entity_connections_query_spec.rb

It seems that `EntityConnectionsQuery.category()` was already meant to accept strings but there was a bug in implementation.
This branch also modifies the web-console whitelist to accept the full range of docker IP addresses.

EntityConnectionsQuery.category() accepts category id as string

---

Gemfile
Gemfile.lock
app/assets/javascripts/pages/bulkAdd.js
app/controllers/relationships_controller.rb
app/helpers/relationships_helper.rb
app/javascript/packs/common/utility.js
app/models/relationship.rb
app/presenters/relationship_details.rb
app/presenters/relationship_label.rb
app/views/relationships/bulk_add.html.erb
app/views/relationships/edit.html.erb
db/migrate/20200528185753_add_currency_to_relationship.rb
db/schema.rb
db/structure.sql
spec/controllers/relationships_controller_bulk_add_spec.rb
spec/models/relationship_spec.rb
spec/presenters/relationship_details_spec.rb
spec/presenters/relationship_label_spec.rb
spec/requests/relationships_spec.rb

Resolves #1106
Requires merge of https://github.com/public-accountability/littlesis-main/pull/30
Note that this only covers financial data directly on the `Relationship` object, which means donations. There are some other places we should probably consider adding currency data:
- positions, which have compensation
- memberships, which have dues 
... but those are another project.

non-USD payments

---

app/models/relationship.rb
db/migrate/20200528185753_add_currency_to_relationship.rb
spec/features/relationship_deletion_spec.rb
spec/models/relationship_spec.rb

resolves #1155 
resolves #1160 
SQL to run on production:
``` sql
UPDATE relationship SET currency = 'usd' WHERE currency = 'USD'
```

fix "USD" currency validation bugs

---

app/utility/ls_date.rb
spec/utility/ls_date_spec.rb
spec/validators/date_validator_spec.rb

Closes #946.
Allows dates in **Month Day, Year** and **Month Day Year** formats.
Note that this uses `DateTime.parse` and then essentially adds to this handling for dates of the format 2000-00-00, and 2000-01-00, which are peculiar to LittleSis.

Handle new date format

---

app/views/entities/_relationships.html.erb

Not ideal to be doing this in the view, but unavoidable without significant refactoring.
Since this is in the view and controller specs don't render views, we also can't put a test for this in the controller spec.
Resolves #554.

Prevent infinite pagination

---

.eslintrc
app/javascript/packs/components/new_reference_modal.js
app/views/shared/_reference_new.html.erb
config/webpacker.yml
package.json
spec/features/js/adding_a_reference_to_a_list_spec.rb
spec/utility/entity_matcher_spec.rb
yarn.lock

This represents a proposal for an extremely simple approach to migrating existing JS into Webpacker:
1. Write a Selenium spec against the existing JS feature and get it passing
2. Move it into `app/javascript/packs/components/` and include it in the relevant place with `javascript_pack_tag 'components/somefile'`
3. Check the spec still passes
After spending a fair bit of time reading around about approaches, there doesn't seem to be much consensus on the wrong or right way; this one has the virtue of being minimal and easy. If we want to do larger refactorings of the LittleSis JS, that can be separated from the migration to Webpacker.
Additionally, this PR:
1. sets up ESLint for `littlesis-rails`, along similar lines to what we use for Oligrapher
2. configures Webpacker to use a dev …

Move referenceModal.js to webpacker

---

app/models/user.rb
app/views/entities/_image_table_row.html.erb
app/views/images/crop.html.erb
config/routes.rb
spec/features/images_spec.rb
spec/features/js/browsing_an_entitys_references_spec.rb
spec/models/user_spec.rb
spec/routes/images_spec.rb

Rails by default [defines asset URL helpers](https://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html) which enable routing to items in the asset pipeline without knowing what their actual path will be at any given point. Among these are `image_path` and `image_url`.
LittleSis has an `Image` model and associated resource-routed controller. The default routing URL helper-generation logic for this produces helpers named `image_path` and `image_url`, thus over-writing the asset helpers.
This PR thus distinguishes the image resource routing helpers from the asset pipeline image helpers, so that:
* `image_(path|url)` now works as an asset URL helper
* `ls_image_(path|url)` etc route to `images_controller`

Broken image asset routes

---

app/controllers/home_controller.rb
app/controllers/users/sessions_controller.rb
app/views/entities/edit.html.erb
spec/features/login_spec.rb
spec/support/notice_helpers.rb

Restores default expected behaviour of a login process, i.e. to take the user back to what they were trying to access before being prompted to log in, rather than sending all users to the dashboard, which is probably not what most people want.

Redirect after authentication

---

config/initializers/html_sanitizer.rb

Video iframes have disappeared on the help page since we moved to Trix/ActionText

Allow iframes in HTML content

---

app/views/lists/edit.html.erb
app/views/lists/interlocks/companies.html.erb
app/views/lists/interlocks/funding.html.erb
app/views/lists/interlocks/giving.html.erb
app/views/lists/interlocks/government.html.erb
app/views/lists/interlocks/index.html.erb
app/views/lists/interlocks/other_orgs.html.erb
app/views/lists/members.html.erb
app/views/lists/modifications.html.erb
app/views/lists/references.html.erb

#1673
Might be worth refactor, but now there is a consistency in page titles in the app/views/lists directory:
And here is the fixed page title:

consistent list page titles

---

DEVELOPMENT.md

Rspec binary is installed via gems/bundler. Since there is no custom script in bin/ directory just invoke rspec directly on the app container.

fix: command to invoke tests
